### ISSUE TITLE
[bug] lint-staged

### ISSUE THREAD

**Issue by TorinAsakura** [Atlantis-Lab/config#91]
### Описание бага
1. **@atlantis-lab/prettier-config@latest**
2. actl commit

При попытке сделать коммит у нас на проектах висят husky с хуками на precommit и commit-msg, если в стейдже нет файлов мы ловим ошибку после чего коммит прерывается.
   
### Воспроизведение
Шаги для воспроизведения бага:
1. Создай репу
2. Насри файлами
3. создай блок вида https://github.com/Atlantis-Lab/serenity/blob/dev/package.json#L32
4. git add .
5. actl commit 

### Ожидаемое поведение
линт-стейджед ничего не нашёл, мы успешно коммитнули файлы

### Материалы
```js
husky > pre-commit (node v14.14.0)
Could not parse lint-staged config.

        Error: ● Validation Error:

Invalid value for 'default'.

Should be a string, a function, or an array of strings and functions.

Configured value is: {'*.{js,ts,tsx,yml,yaml,json,graphql,md}': ['prettier --write --config /Users/torinasakura/workspace/atlantis/serenity/node_modules/@atlantis-lab/prettier-config/dist/index.js --ignore-path /Users/torinasakura/workspace/atlantis/serenity/node_modules/@atlantis-lab/prettier-config/.prettierignore', 'git add'], '*.{ts,tsx}': ['bash -c "tsc --noEmit"'], '*.{js,jsx,ts,tsx}': ['eslint --fix --config /Users/torinasakura/workspace/atlantis/serenity/node_modules/@atlantis-lab/eslint-config/dist/index.js', 'jest --config /Users/torinasakura/workspace/atlantis/serenity/node_modules/@atlantis-lab/jest-config/dist/index.js --bail --findRelatedTests', 'git add']}

Please refer to https://github.com/okonet/lint-staged#configuration for more information...

Please make sure you have created it correctly.
See https://github.com/okonet/lint-staged#configuration.

husky > pre-commit hook failed (add --no-verify to bypass)
/Users/torinasakura/workspace/atlantis/serenity/node_modules/commitizen/dist/cli/strategies/git-cz.js:85
        throw error;
        ^

Error: git exited with error code 1
    at ChildProcess.<anonymous> (/Users/torinasakura/workspace/atlantis/serenity/node_modules/commitizen/dist/git/commit.js:807:28)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 1,
  signal: null
}
```

### Данные окружения
 - **nodeJS**: 14.14.0
 - **yarn**: 1.22.10
 - **atlantis-lab/actl**: latest

**Comment by TFK70** [comment]
@TorinAsakura проблема аналогичная https://github.com/Atlantis-Lab/config/issues/83
Создам таску на исследование этого, пока экспорты в проблемных придется на cjs'ные заменить

**Comment by TFK70** [comment]
Closed with https://github.com/Atlantis-Lab/actl/issues/100
